### ISSUE TITLE
LoginAttempt.php:11

### ISSUE THREAD

**Issue by neokofg** [mikebronner/laravel-mixpanel#107]
Error: Cannot use object of type Illuminate\Auth\Events\Attempting as array in projectname/vendor/genealabs/laravel-mixpanel/src/Listeners/LoginAttempt.php:11

`$email = $event->credentials['email'] ?? $event['email'] ?? '';`
i think it should be like this
`$email = $event->credentials['email'] ?? '';`

**Comment by mikebronner** [comment]
@neokofg thank you for writing in. Could you submit a test repo with the failure, or alternatively create a phpunit test with the failure as a PR?

**Comment by bajarang-agarwal** [comment]
@mikebronner 

We are also getting the same error.

In LoginAttempt.php, we printed the following line
> \Log::info($event->credentials);

it printed as:
>  array (
  'code' => 'cJ8U-3kn9FUnup05opsNYgL8_xeQcYarwL9kMjlS3gg',
  'state' => '6aef979c21f2ab6ff80b85cde466d6',
)  

If you notice this does not have email in the credentials object. 
On a side note, we are using Auth0 and Auth0 does not return the email so it might be an issue.

**Comment by mikebronner** [comment]
This should be fixed in release 11.0.1. Please open a new ticket with a complete stack trace if it still is erroring.
