### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by gpassarelli** [mikebronner/laravel-mixpanel#108]
Would it be possible to update the package to add Laravel 10 support?
One of the forks already had implemented some changes:
https://github.com/moynzzz/laravel-mixpanel/commit/264ef29c6a0f5dfd2080199396019a435231a866

**Comment by mikebronner** [comment]
Thanks for the reminder, I'll update that ASAP.

**Comment by gabriel-ixm** [comment]
@mikebronner any updates on this?
I've tried to create  PR from the fork that has already implemented this, but I couldn't as I'm not a colaborator of this project. perhaps you could?
https://github.com/mikebronner/laravel-mixpanel/compare/master...moynzzz:laravel-mixpanel:add-laravel-10-support

**Comment by gpassarelli** [comment]
@mikebronner any updates on this?
I've tried to create  PR from the fork that has already implemented this, but I couldn't as I'm not a colaborator of this project. perhaps you could?
https://github.com/mikebronner/laravel-mixpanel/compare/master...moynzzz:laravel-mixpanel:add-laravel-10-support

**Comment by mikebronner** [comment]
@gpassarelli It should work with Laravel 10, an update for this was released 3 weeks ago. Are you having issues getting it working?

Fixed by #110 

(closing this for now, please open a new issue if you are having problems)
