### ISSUE TITLE
Custom defaults events

### ISSUE THREAD

**Issue by pixsolution** [mikebronner/laravel-mixpanel#89]
Hello!  Your package brings default events like login, registration, etc. How do I customize the names of these events?  how/where do I add other properties for these defaults events ex.  first login, last login, lifetime login ....?

**Comment by mikebronner** [comment]
These events are based on internal Laravel events, and cannot be customized. You would have to wire up your own events and implement your own mixpanel updates based on those. You can use the Listeners in this package as examples. Good luck!
